config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks"}

  resources :restaurants do 
    resources :reviews
    resources :users
  end 

  resources :users, :only => [:show]

root to: "application#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :location, presence: true

    has_many :reviews, dependent: :destroy
    has_many :users, through: :reviews

    accepts_nested_attributes_for :reviews

    def self.search(search)
        if search 
           @restaurant  = Restaurant.find_by(location: search)
            if @restaurant  
                self.where(location: search)
            else 
                Restaurant.all
            end 
        else 
            Restaurant.all
        end 
    end 
end 

app/models/review.rb
class Review < ApplicationRecord
    validates :message, presence: true
    validates :stars, presence: true
    
    belongs_to :user
    belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, 
    :omniauthable

    has_many :reviews
    has_many :restaurants, through: :reviews

    def self.google_omniauth(auth)
      where(provider: auth["provider"], uid: auth["uid"]).first_or_create(email: auth["info"]["email"]) do |user|
        user.image = auth.info.image
        user.name = auth.info.name
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
 before_action :authenticate_user!, except: :google_oauth2

    def google_oauth2
        @user = User.google_omniauth(request.env['omniauth.auth'])
        sign_in_and_redirect @user
    end
end 

app/controllers/registration_controller.rb
class RegistrationsController < ApplicationController
    
    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
#overwriting the devise's default strong params to include: name, username and image
    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :image, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :image, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

    def index
      @restaurants = Restaurant.search(params[:search])
    end
  
    def show
    end
  
    def new
      @restaurant = Restaurant.new
      @restaurant.reviews.build
    end

    def create
        # binding.pry
      @restaurant = current_user.restaurants.build(restaurant_params)
      #  binding.pry
      if @restaurant.save
        redirect_to restaurant_path(@restaurant)
      else
        render :new, notice: "Could not create restaurant"
      end
    end

    def edit 
    end 

    def update
      if @restaurant
        @restaurant.update(restaurant_params)
        if @restaurant.errors.any?
          render "edit"
        else
          redirect_to @restaurant
        end
      else
        render "edit", notice: "Could not edit this restaurant"
      end
    end
  
    def destroy
      @restaurant.destroy
      redirect_to restaurants_path
    end

    private

    def set_restaurant
      @restaurant = Restaurant.find_by_id(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :location, :search, reviews_attributes: [:id, :message, :stars, :user_id, :restaurant_id])
    end 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :new, :create]
  before_action :set_review,  only: [:show, :edit, :update, :destroy]


  def index
    if params[:restaurant_id]
      set_restaurant
      @reviews = @restaurant.reviews
    else
      @reviews = Review.order(:updated_at || :created_at).reverse
    end
  end

  def show
  end

  def new
    if params[:restaurant_id]
      set_restaurant
      @review = @restaurant.reviews.build
    else
      @review = Review.new
    end
  end

  def create
    # binding.pry
    if params[:restaurant_id]
      set_restaurant
      @review = @restaurant.reviews.build(review_params)
      @review.user_id =  current_user.id
    else
      @review = current_user.reviews.build(review_params)
  # binding.pry
     end
    if @review.save
      if @restaurant
         redirect_to restaurant_review_path(@restaurant, @review)
      else
        redirect_to @review 
      end
    else
      render :new, notice: "Could not create review"
    end
  end

  def edit
    # if !current_user.id = @review.user_id
    # redirect_to restaurant_review_path, notice: "Unable to edit this review" 
    # end 
  end

  def update
    if @review
      @review.update(review_params)
      if @review.errors.any?
        render "edit"
      else
        redirect_to restaurant_review_path
      end
    else
      render "edit"
    end
  end

  def destroy
    @review.destroy
    redirect_to restaurant_reviews_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find_by_id(params[:restaurant_id])
  end

  def set_review
    @review = Review.find_by_id(params[:id])
  end

  def review_params
    params.require(:review).permit(:message, :stars, :search)
  end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        if user_signed_in?
        @user = current_user 
        end
    end 

    def index
    if params[:restaurant_id]
        @restaurant = Restaurant.find_by_id(params[:restaurant_id])
        @users = @restaurant.users
    end 
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/application/home.html.erb
<div class="col-xs-1 text-center" >
    <% if user_signed_in? %>
        <div class="card mb-3 center" style=" height: 80px; background-color: #e9fffee6">
            <div class="card-body">
                <h2>Hello, <%= link_to current_user.name.titleize, edit_user_registration_path %> </h2>
            </div>
        </div>
        <div class="fade-in"><img class="edit-image" src=https://www.freelogodesign.org/file/app/client/thumb/dcb5fc67-e9fa-4287-9288-49cfbcf898b8_200x200.png?1604445793414"; style="width: 500px; height: 500px; margin: 0px;"></div><br />
            <h5><%= link_to "Enter a New Restaurant", new_restaurant_path %></h5>
            <h6><%= link_to "See Restaurants", restaurants_path %></h6>
    <% else %>
            <div class="fade-in"><img class="edit-image" src=https://www.freelogodesign.org/file/app/client/thumb/dcb5fc67-e9fa-4287-9288-49cfbcf898b8_200x200.png?1604445793414"; style="width: 500px; height: 500px; margin: 0px;"></div><br />
            <p>Review your favorite restaurants and discover restaurants around your area!</p>
    <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">LET'S TACO BOUT IT</a>
  <img src=https://www.freelogodesign.org/file/app/client/thumb/dcb5fc67-e9fa-4287-9288-49cfbcf898b8_200x200.png?1604445793414"; style="width: 50px; height: 50px; margin: 0px;">
 


  <div class="navbar-collapse collapse show" id="navbarColor01" style="">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

      <% if user_signed_in? %>
          <li> <%= link_to 'Restaurants', restaurants_path, class: "nav-link" %> </li>
          <li> <%= link_to "View your Reviews", user_path(current_user), class: "nav-link" %> </li>
        
      <% else %>
          <li class="nav-item"><%= link_to 'Log in', new_user_session_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %></li>
      <%end %>
    </ul>
    <% if user_signed_in? %>
        <p class="nav-item"><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link text-secondary" %></p>
        <a href='http://localhost:3000/users/edit'><src="<%=image_tag current_user.image, class: "img-fluid rounded-circle", style: "height: 2rem"%>
        <p> <%= image_tag current_user.image, class: "img-fluid rounded-circle", style: "height: 2rem"%></a></p>
        <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Frijole&display=swap" rel="stylesheet">

  <title> TACO BOUT IT </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
  
  <%= render 'layouts/nav' %>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <%= yield %>

  </body>
</html>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
        <h5 class="error"><%= @restaurant.errors.full_messages.to_sentence %></h5>
<% end %>

<%= form_with model: @restaurant, local: true do |f| %>
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name, class: @restaurant.errors.any? ? "error-field" : nil %>

    <%= f.label :location, "City:" %>
    <%= f.text_field :location %>

    <%= f.submit class: "btn btn-outline-secondary btn-sm" %>
<%end %>

app/views/restaurants/edit.html.erb
<div class="field">
  <h1> Update:</h1>
   <%= render 'form' %>
</div>

app/views/restaurants/index.html.erb
<h4> Search by City: </h4>
<%= form_tag(restaurants_path, method: :get) do %>
    <select name="search">
      <option value="">All</option>
      <%# collect and call a unique on the result %>
      <% Restaurant.all.each do |rest| %>
        <option value="<%= rest.location %>"><%= rest.location %></option>
      <% end %>
    </select>

<%= submit_tag ("Search"), class: "btn btn-outline-secondary btn-sm" %>
<% end %>

 <div class="card mb-3" style=" height: 60px; border-color: #80c2c4">
    <div class="card-body">
      <h2 class="text-center"> Restaurants: </h2><br />
    </div>
</div>

<% @restaurants.each do |res| %> 
  <div class="card mb-3" style="width: 100%; height: 60px; background-color: #80c2c4">
    <div class="card-body text-center">
    <p class="card-text"><%= link_to "#{res.name.titleize}  |  #{res.location}  |  #{res.reviews.average(:stars)}", res %>&#9733</p>
    </div>
  </div>
<% end %><br />
   
<p class="text-center"><%= link_to "Add a New Restaurant", new_restaurant_path %></p>

app/views/restaurants/new.html.erb
  <div class="field">
    <h1> Restaurant</h1>
    <%= render 'form' %>
   </div>

app/views/restaurants/show.html.erb
<div class="card">
    <div class="card-body">
      <h2 class="card-title">Restaurant: <%= @restaurant.name.titleize %></h2>
      <h4 class="card-subtitle mb-2 text-muted">City: <%= @restaurant.location %></h4>

        <ul>
          <% @restaurant.reviews.each do | rv | %>
            <li><%= rv.message %> |  <%= rv.stars %>&#9733</li>
          <% end %>
        </ul>
    </div>

  <h6><%= link_to "Enter Review", new_restaurant_review_path(@restaurant), class: "btn btn-outline-secondary btn-sm" %></h6>
  <h6><%= link_to "View Reviews",restaurant_review_path(@restaurant), class: "btn btn-outline-secondary btn-sm" %></h6>
</div><br />

<h6> <%= link_to "Update Restaurant's Info", edit_restaurant_path(@restaurant)%> </h6>
<h6><%= link_to("Delete Restaurant", @restaurant, method: :delete, data:{confirm: "Do you really want to delete this?"}) %></h6>

app/views/reviews/_form.html.erb
<% if @review.errors.any? %>
        <h5 class="error"><%= @review.errors.full_messages.to_sentence %></h5>
<% end %>

<%= form_with model: [@restaurant, @review], local: true do | r | %>
    <%= r.label :message, "Review:" %>
    <%= r.text_area :message %>
    
    <%= r.label :stars %>
    <%= r.number_field :stars, min: "0", max: "5"%> 

        <%= r.submit class: "btn btn-outline-secondary btn-sm" %>
<% end %>

app/views/reviews/edit.html.erb
<div class="field">
    <h3> Edit Review: </h3>
    <%= render 'form'%>
</div>

app/views/reviews/index.html.erb
<% if @restaurant %>
    <h1><%= link_to @restaurant.name.titleize, restaurant_path(@restaurant) %>'s Reviews:</h1>
<% else %>
    <h1>Here Are The Reviews:</h1>
<% end %>

<option selected="">Stars</option>
<select name="restaurant[review_id]" id="restaurant_review_id">
        <% Review.all.uniq.each do |res| %>
        <option value="<%= res.id %>"><%= res.stars %></option>
    <% end %>
</select>

 <blockquote class="blockquote">
   <br /> <ul>
        <% @restaurant.reviews.each do |i| %>
            <div class="card text-white bg-dark mb-3" style="width: 90rem;">
                <div class="card-body">
                    <p class="card-text"> <%= i.message %> | <%= i.stars %> &#9733</p>
                     <footer class="blockquote-footer text-right"> <%= i.created_at.strftime("%b-%e-%Y")%> </footer><br /> 
                        <% if i.user.id == current_user.id %>
                        <h6> <%= link_to "Edit Review", edit_restaurant_review_path(@restaurant, i)%> | <%= link_to("Delete Review", @review, method: :delete, data:{confirm: "Do you really want to delete this?"}) %></h6>
                        <% end %>
                </div>
            </div>
        <% end %>
    </ul>
</blockquote>
<%= link_to "Back", :back %>

app/views/reviews/new.html.erb
<div class="field">
  <h1> Review: </h1>
  <%= render 'form' %>
</div>

app/views/reviews/show.html.erb
<% if @restaurant %>
    <h1><%= link_to @restaurant.name, restaurant_path(@restaurant) %>'s reviews:</h1>
<% end %>

<blockquote class="blockquote">
<br /> <ul>
    <% @restaurant.reviews.each do | i | %>
        <div class="card text-white bg-dark mb-3" style="width: 90rem;">
        <div class="card-body">

            <p class="card-text"> <%= i.message %> | <%= i.stars %> &#9733</p>
            <footer class="blockquote-footer text-right"> <%= i.created_at.strftime("%b-%e-%Y") %></footer><br />
            <% if i.user.id == current_user.id %> 
            <h6><%= link_to "Edit Review", edit_restaurant_review_path(@restaurant, i)%> | <%= link_to("Delete", restaurant_review_path(@restaurant, i), method: :delete, data:{confirm: "Are you sure?"}) %></h6>
             <% end %>
        </div>
        </div>
    <% end %>
    </ul>
</blockquote>

app/views/users/index.html.erb
<ul>
        <% @users.each do |i| %>
            <div class="card text-white bg-dark mb-3" style="width: 90rem;">
                <div class="card-body">
                <%= i.name %>
                 <% end %>
                </div>
            </div>
            </ul>

app/views/users/show.html.erb
 <div class="card mb-3" style=" height: 60px; border-color: #87dbf0">
    <div class="card-body">
      <h2 class="text-center"> Your Reviews: </h2><br />
    </div>
</div>

 <blockquote class="blockquote">
   <br /> <ul>
        <% @user.reviews.each do |i| %>
            <div class="card text-grey mb-3" style="width: 90rem; background-color: #87dbf0">
            <div class="card-header"><%= i.restaurant.name %></div>
                <div class="card-body">
                    <p class="card-text"> <%= i.message %> | <%= i.stars %> &#9733</p>
                     <footer class="blockquote-footer text-right"> <%= i.created_at.strftime("%b-%e-%Y")%> </footer><br /> 
                        <% if i.user.id == current_user.id %>
                        <h6> <%= link_to "Edit Review", edit_restaurant_review_path(@user, i)%> | <%= link_to("Delete Review", @review, method: :delete, data:{confirm: "Do you really want to delete this?"}) %></h6>
                        <% end %>
                </div>
            </div>
        <% end %>
    </ul>
</blockquote>